website/auth.py
# Import required modules
from flask import Flask, render_template, request, Blueprint, url_for, redirect, session, flash
from google.cloud import datastore
import bcrypt
import os
import datetime
import random


# Create a Flask app
auth = Blueprint('auth', __name__)

# Initialize Datastore client
datastore_client = datastore.Client()



@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        # Get form data from request
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm-password']
        
        
        # Check if password and confirm password match
        if password != confirm_password:
            flash('Password and Confirm Password do not match', 'danger')
            return redirect('/signup')

        # Check if user already exists in Datastore
        query = datastore_client.query(kind='CustomerData')
        query.add_filter('Email', '=', email)
        existing_users = query.fetch()

        if len(list(existing_users)) > 0:
            flash('User with this email already exists', 'danger')
            return redirect('/signup')
        
        current_datetime = datetime.datetime.now()
        random_number = random.randint(100, 999)  # Adjust range as needed
        Customer_ID = f'C{current_datetime.strftime("%Y%m%d%H%M%S")}_{random_number}'

        # Save new user to Datastore
        user_key = datastore_client.key('CustomerData', Customer_ID)  # Use email as the key
        user = datastore.Entity(key=user_key)

        user['First_Name'] = name
        user['Email'] = email
        user['Password'] = password
        user['Customer_ID'] = Customer_ID
        datastore_client.put(user)

        flash("Account Created Successfully!", "success")
        return redirect('/login')

    else:
        
        # Render the signup page for GET request
        return render_template('signup_page.html')


@auth.route('/reset_password', methods=['GET', 'POST'])
def reset_password():

    
        if request.method == 'POST':
            email = request.form['email']
            new_password = request.form['new_password']

            # Check if email and new password are provided
            if not email or not new_password:
                return 'Email and new password are required', 400

            # Query Datastore to check if email exists
            query = datastore_client.query(kind='User')
            query.add_filter('email', '=', email)
            result = list(query.fetch())  # Convert query result to list

            # If a user with the given email is found
            if len(result) > 0:
                user = result[0]

                # Update user's password in Datastore
                
                hashed_password = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt())
                user['password'] = hashed_password.decode('utf-8')                            
                datastore_client.put(user)

                return redirect('/login')
            
            else:
                flash("No account exist with this email","error")
                return redirect('/reset_password')

        else:
            return render_template('reset_password.html')
   
# Initialize Google Cloud Datastore client
datastore_client = datastore.Client()

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Get email and password from form data
        email = request.form.get('email')
        password = request.form.get('password')

        # Validate input
        if not email:
            flash('Please enter your email', 'error')
            return redirect('/login')
        if not password:
            flash('Please enter your password', 'error')
            return redirect('/login')

        # Query Datastore for user with matching email
        query = datastore_client.query(kind='CustomerData')
        query.add_filter('Email', '=', email)
        result = list(query.fetch(limit=1))

        if result:
            # User found, retrieve user information
            user = result[0]
            stored_password = user['Password']  # Retrieve the stored password from the dataset

            # Validate password
            if password == stored_password:
                # Passwords match, log in user
                session['customer_id'] = user.get('Customer_ID')
                session['first_name'] = user.get('First_Name')
                session['last_name'] = user.get('Last_Name')
                print(user.get('First_Name'))

                # Assuming you have a user role field in your dataset
                # user_role = user['User_Role']
                # You can adjust the role logic here

                return redirect('/home')  # Replace with the appropriate route
            else:
                # Incorrect password
                flash('Incorrect password', 'danger')
                return redirect('/login')
        else:
            # User not found
            flash('Incorrect email', 'danger')
            return redirect('/login')
    else:
        # Render login page
        if 'customer_id' in session:
            return redirect('/homepage')  # Replace with the appropriate route
        return render_template('login.html')

@auth.route('/logout')
def logout():
    # Logout logic here
    session.clear()
    return redirect('/login')






 

website/views.py
from flask import jsonify, request, render_template
from flask import Blueprint, render_template, url_for, request, session, redirect, Flask, jsonify, flash, make_response
from google.cloud import datastore
from google.cloud import vision_v1
from google.cloud.vision_v1 import types
from colorthief import ColorThief
from google.cloud import storage, vision
from werkzeug.utils import secure_filename
import io
import json
import datetime
import hashlib
import random
import string
import os
import google.generativeai as palm
from google.cloud import storage
from google.cloud import datastore
import requests
from typing import Sequence
import re

views = Blueprint('views', __name__)


BASE_URL = "https://drzz-services-kcvokjzgdq-nw.a.run.app"

@views.route('/')
def home():
    return redirect('/home')






# Function to fetch products with pagination
def fetch_products(page, per_page):
    
    endpoint = '/service/product/all_products'
    api_url = f'{BASE_URL}{endpoint}'

    response = requests.get(api_url)  # Replace with your actual API URL
    products = response.json()

    total_products = len(products)
    start_idx = (page - 1) * per_page
    end_idx = start_idx + per_page
    paginated_products = products[start_idx:end_idx]

    return paginated_products, total_products


# Route to render HTML page and display products with pagination
@views.route('/home')
def homepage():
    page = request.args.get('page', default=1, type=int)  # Get the requested page number from the URL
    per_page = 8 # Number of products per page

    products, total_products = fetch_products(page, per_page)  # Fetch products using the API

    total_pages = (total_products + per_page - 1) // per_page  # Calculate the total number of pages

    return render_template('homepage.html', products=products, page=page, per_page=per_page, total_pages=total_pages)





# Existing routes and functions...

@views.route('/product/<string:product_id>')
def product_details(product_id):
    endpoint = '/service/product/id'
    api_url = f"{BASE_URL}{endpoint}"
    response = requests.post(api_url,json={"product_id": product_id})
    product_data = response.json()

    return render_template('product_description.html', product=product_data)







def fetch_products_styleme():
    endpoint = '/service/product/all_products'
    api_url = f"{BASE_URL}{endpoint}"
    response = requests.get(api_url)  # Replace with your actual API URL
    products = response.json()
    return products[:3]


@views.route('/conversation')
def conversation():
     
    products = fetch_products_styleme() 
     
    return render_template('conversation.html', products=products)







def ask_question_from_fashion(data):
    try:
        
        endpoint = '/service/ai/fashionqna'
        api_url = f"{BASE_URL}{endpoint}"
        payload = {
            'question': data
            
        }
        response = requests.post(api_url, json=payload)
        response.raise_for_status()  # Raise an exception for HTTP errors
        return response.json().get('answer', 'Sorry, I couldn\'t find an answer.')
    except requests.exceptions.RequestException as e:
        # Handle the exception and return an error response
        return 'An error occurred while communicating with the chatbot.'
# Initialize an empty list to store the conversation
#conversation_list = []
 
@views.route('/stylemeqna', methods=['POST'])
def styleme_qna():
    # Get the magazine_id from the session
    conversation_list = []
    user_question = request.json.get('question')
    if not user_question:
        return jsonify({'error': 'Empty question.'}), 400
    prompt = "\n".join(user_question) + "\n\n You are a Fashion advisor read user_question above and give response as a real Fashion advisor would give ."
    chat = convert_conversation_list_to_plain_text(conversation_list)
    data = {"content": prompt}
    
    answer = ask_question_from_fashion(data)
        
    conversation_list.append({'User': user_question, 'Fashion Advisor': answer})
    #print(conversation_list)
    # Return the answer as a JSON response
    return jsonify({'answer': answer})



def get_products_by_ids(product_ids):
    try:
        # Make a POST request to the cloud function for each product ID
        product_details = []
        print(product_ids)
        for product_id in product_ids['product_ids']:
            print(product_id)

            endpoint = '/service/product/id'
            api_url = f"{BASE_URL}{endpoint}"
            response = requests.post(api_url, json={"product_id": product_id})
            
            if response.status_code == 200:
                response_data = response.json()  # Parse the response JSON
                product_details.append(response_data)
            else:
                # Handle the error response if needed
                print(f"Failed to fetch details for product ID {product_id}: {response.status_code}")

        return product_details

    except Exception as e:
        return {
            "message": str(e)
        }    

# Define the URL of the second Cloud Run service




def convert_conversation_list_to_plain_text(conversation_list):
  """
  Converts a conversation list to plain text.

  Args:
    conversation_list: A list of conversation objects.

  Returns:
    A string of plain text representing the conversation.
  """

  plain_text = ""
  for conversation in conversation_list:
    plain_text += f"User: {conversation['User']}\n"
    plain_text += f"Fashion Advisor: {conversation['Fashion Advisor']}\n"
    print(plain_text)
  return plain_text



@views.route('/styleme', methods=['POST', 'GET'])
def styleme():
    if request.method == 'POST':
        try:
            request_data = request.get_json()
            conversation_list = request_data.get('conversation')
            chat = convert_conversation_list_to_plain_text(conversation_list)
            conversation = parse_conversation(chat)
            chat_conversation = {"conversation": conversation}
            
            response_message = store_conversation_in_datastore(chat_conversation)

            data = {"chat": chat}
            endpoint = '/service/ai/demographic_json'
            api_url = f"{BASE_URL}{endpoint}"

            response_post = requests.post(api_url, json=data)

            if response_post.status_code == 200:
                summary_dict = json.loads(response_post.json().get("summary", "{}"))
                product_ids = get_product_by_json_summary(summary_dict)
                products = get_products_by_id(product_ids)
                session['products'] = products
                

                # Return products and product details as JSON
                return jsonify(products=products)

        except Exception as e:
            print("Error:", str(e))

        # If any error occurs or no products are found, return an empty JSON
        return jsonify(products=[])

    else:
        products = fetch_products_styleme()
        return render_template('styleme.html', products=products)
        


# Function to get articles for a magazine
def get_articles(magazine_id):
    try:
        endpoint = '/service/get_articles'
        api_url = f"{BASE_URL}{endpoint}"
        response = requests.post(api_url, json={'magazine_id': magazine_id})
        response.raise_for_status()  # Raise an exception for HTTP errors
        return response.json()
    except requests.exceptions.RequestException as e:
        # Handle the exception and return an error response
        return None

# Function to ask a question to the chatbot
def ask_question(user_question, magazine_id, articles):
    try:
        endpoint = '/service/ai/magazine_qna'
        api_url = f"{BASE_URL}{endpoint}"
        payload = {
            'question': user_question,
            'articles': articles,
            'magazine_id': magazine_id
        }
        response = requests.post(api_url, json=payload)
        response.raise_for_status()  # Raise an exception for HTTP errors
        return response.json().get('answer', 'Sorry, I couldn\'t find an answer.')
    except requests.exceptions.RequestException as e:
        # Handle the exception and return an error response
        return 'An error occurred while communicating with the chatbot.'


# Flask route for the magazine page
@views.route('/magazine')
def magazine():
    return render_template('magazine.html')

# Flask route to get articles for a specific magazine
@views.route('/magazine/<magazine_id>')
def magazines(magazine_id):
    # Store the magazine_id in the session
    session['magazine_id'] = magazine_id

    articles = get_articles(magazine_id)
    if articles is None:
        return jsonify({'error': 'An error occurred while fetching articles.'}), 500

    return render_template('magazine.html', articles=articles)

# Flask route to handle user questions
@views.route('/qna', methods=['POST'])
def qna():
    # Get the magazine_id from the session
    magazine_id = session.get('magazine_id')

    if magazine_id is None:
        return jsonify({'error': 'Magazine ID not found in the session.'}), 400

    user_question = request.json.get('question')
    if not user_question:
        return jsonify({'error': 'Empty question.'}), 400

    articles = get_articles(magazine_id)
    if articles is None:
        return jsonify({'error': 'An error occurred while fetching articles.'}), 500

    answer = ask_question(user_question, magazine_id, articles)

    # Return the answer as a JSON response
    return jsonify({'answer': answer})


'''@views.route('/qna', methods=['POST'])
def qna():
    user_question = request.json.get('question')

    # Sample response - you should replace this with your actual logic
    answer = "This is a sample answer to your question: " + user_question

    # Return the answer as JSON
    return jsonify({'answer': answer})'''







    
datastore_client= datastore.Client()
@views.route('/marketing')
def marketing():

website/templates/chathistory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fashion Web Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='chathistory/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    
        <!-- Navigation Bar -->
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('views.homepage') }}">DRZZ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <!-- Navigation Links -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('views.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.styleme') }}">Style Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.magazine') }}">Magazine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.chathistory') }}">Fashion Advisor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.marketing') }}">Marketing</a>
                        </li>        
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.lookalike') }}">Look-Alike</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Shop For
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Men</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Women</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Boys</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Girls</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Wedding</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Party</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Birthday</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Casual</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Formal</a></li>
                            </ul>
                        </li>
                        
                    </ul>
                    <!-- Search Form -->
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <!-- User Authentication Links -->
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    

    
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row">
            <br><br><br>
            <h3 style="font-size: large;margin-top: 20px;">Notes for Stylist</h3>
            <div class="col-md-6">
                <!-- Product Display -->
                <div class="container-fluid product-container">
                    {% for product in products[:3] %}
                    <div class="product">
                        <a href="{{ url_for('views.product_details', product_id=product.product_ID) }}">
                            <img src="{{ product.image_URL }}" alt="{{ product.product_name }}">
                            <h6>{{ product.product_name }}</h6>
                            <p>${{ product.price }}</p>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <!-- Product Display -->
                <div class="product-container">
                    <div class="summary">
                        <p>{{summary}}</p>
                    </div>
                    
                    
                    
                    <!-- Add more product display sections here -->
                    <!-- ... -->
                </div>
                <div class="button-container">
                    <button id="send-button" type="button">Accept Appointment</button>
                </div>
            </div>
        </div>
    </div>
    

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="../static/Stylemepage/scripts.js"></script>
</body>
</html>

website/templates/conversation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fashion Web Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='conversation/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

</head>

<body>
    
        <!-- Navigation Bar -->
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('views.homepage') }}">DRZZ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <!-- Navigation Links -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('views.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.styleme') }}">Style Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.magazine') }}">Magazine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.chathistory') }}">Fashion Advisor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.marketing') }}">Marketing</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.lookalike') }}">Look-Alike</a>
                          </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Shop For
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Men</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Women</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Boys</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Girls</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Wedding</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Party</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Birthday</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Casual</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.homepage') }}">Formal</a></li>
                            </ul>
                        </li>
                        
                    </ul>
                    <!-- Search Form -->
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <!-- User Authentication Links -->
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    <br>

       
        
    <!-- Main Content -->
<div class="container-fluid">
    <div class="row">
        <!-- Product Display -->
        <div class="col-md-6">
            <div class="container-fluid product-container" >
                    {% for product in products %}
                    <div class="product">
                        <a href="{{ url_for('views.product_details', product_id=product.product_ID) }}">
                            <img src="{{ product.image_URL }}" alt="{{ product.product_name }}">
                            <h2>{{ product.product_name }}</h2>
                            <p>${{ product.price }}</p>
                        </a>   
                    </div>
                    {% endfor %}
                </div>
        </div>
        <!-- Chatbot Container (Moved to the Left) -->
        <div class="col-md-6">
            <div class="chat-container">
                <div class="chat-box" id="chat-box">
                    <!-- Bot messages will be displayed here -->
                    <div class="message bot-message">Hello! How can I assist you today?</div>
                </div>
                <div class="input-container">
                    <input id="user-input" class="form-control" type="text" placeholder="Type your message...">
                    <button id="send-button" class="btn btn-outline-secondary">Send</button>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Add a button and a hidden summary section -->
<button id="summary-button" class="btn btn-primary">Show Summary</button>
<div id="summary" class="summary">
    <!-- Your summary content goes here -->
    <p>This is the summary text. It can contain any information you want to display.</p>
</div>


            

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="../static/conversation/scripts.js"></script>
    
</body>
</html>